// <auto-generated />
using System;
using FixItApp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixItApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230328180506_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.ApplicationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MasterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MasterId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.FeedbackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "2e8a6318-18e0-41c0-9c3a-7ef24a6b4984",
                            Name = "Customer"
                        },
                        new
                        {
                            Id = "db7ac1bc-08ed-42c5-bc6e-5eeb2a8be9bd",
                            Name = "Master"
                        },
                        new
                        {
                            Id = "8c221bc8-307f-47b9-896c-1eb0019e2e7f",
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.ApplicationEntity", b =>
                {
                    b.HasOne("FixItApp.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("Applications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixItApp.Infrastructure.Entities.UserEntity", "Master")
                        .WithOne()
                        .HasForeignKey("FixItApp.Infrastructure.Entities.ApplicationEntity", "MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.FeedbackEntity", b =>
                {
                    b.HasOne("FixItApp.Infrastructure.Entities.ApplicationEntity", "Application")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.ItemEntity", b =>
                {
                    b.HasOne("FixItApp.Infrastructure.Entities.ApplicationEntity", "Application")
                        .WithMany("Items")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.UserEntity", b =>
                {
                    b.HasOne("FixItApp.Infrastructure.Entities.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FixItApp.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
